var cats = [ '卷毛猫',
  '西伯利亚猫',
  '金吉拉猫',
  '山东狮子猫',
  '安哥拉猫',
  '玳瑁猫',
  '伯曼猫',
  '缅因猫',
  '缅甸猫',
  '雪鞋猫',
  '短腿猫',
  '土耳其梵猫',
  '埃及猫',
  '孟买猫',
  '加拿大无毛猫',
  '俄罗斯蓝猫',
  '苏格兰折耳猫',
  '孟加拉豹猫',
  '虎斑猫',
  '茶杯猫',
  '狸花猫',
  '异国短毛猫',
  '美国短毛猫',
  '英国短毛猫',
  '布偶猫',
  '波斯猫',
  '暹罗猫' ];

var colors= [ { url: 'http://www.peise.net/color/1.html',
    name: '艾利斯兰',
    color: '#ddf0ed',
    rcolor: '#220f12' },
  { url: 'http://www.peise.net/color/1.html',
    name: '清漾青',
    color: '#376956',
    rcolor: '#c8caa9' },
  { url: 'http://www.peise.net/color/1.html',
    name: '樱花紫',
    color: '#c3bed4',
    rcolor: '#3c412b' },
  { url: 'http://www.peise.net/color/1.html',
    name: '水墨蓝',
    color: '#495a80',
    rcolor: '#b6a5bf' },
  { url: 'http://www.peise.net/color/1.html',
    name: '渌水荡漾清猿啼',
    color: '#c7ffec',
    rcolor: '#380013' },
  { url: 'http://www.peise.net/color/1.html',
    name: '樱草色',
    color: '#e9f01d',
    rcolor: '#160fe2' },
  { url: 'http://www.peise.net/color/1.html',
    name: '暗蓝光紫',
    color: '#9966cc',
    rcolor: '#669933' },
  { url: 'http://www.peise.net/color/1.html',
    name: '霓虹绿',
    color: '#00ff80',
    rcolor: '#ff00bf' },
  { url: 'http://www.peise.net/color/1.html',
    name: '淡麒麟色',
    color: '#eee8ab',
    rcolor: '#111754' },
  { url: 'http://www.peise.net/color/1.html',
    name: '暗卡其色',
    color: '#bdb76a',
    rcolor: '#4248ca' },
  { url: 'http://www.peise.net/color/1.html',
    name: '松石绿',
    color: '#008573',
    rcolor: '#ffbcc5' },
  { url: 'http://www.peise.net/color/1.html',
    name: '雨林绿',
    color: '#00755e',
    rcolor: '#ffc4a1' },
  { url: 'http://www.peise.net/color/1.html',
    name: '风滚草色',
    color: '#dea681',
    rcolor: '#2159be' },
  { url: 'http://www.peise.net/color/1.html',
    name: '灰褐色',
    color: '#483c32',
    rcolor: '#b7c3cd' },
  { url: 'http://www.peise.net/color/1.html',
    name: '西瓜红',
    color: '#fd5b78',
    rcolor: '#02a4c3' },
  { url: 'http://www.peise.net/color/1.html',
    name: '夕阳红',
    color: '#fe4c40',
    rcolor: '#01b3bf' },
  { url: 'http://www.peise.net/color/1.html',
    name: '水红色',
    color: '#de3163',
    rcolor: '#21ce9c' },
  { url: 'http://www.peise.net/color/1.html',
    name: '焦棕色',
    color: '#8a3324',
    rcolor: '#baccdb' },
  { url: 'http://www.peise.net/color/1.html',
    name: '月亮蓝',
    color: '#eeeeff',
    rcolor: '#111100' },
  { url: 'http://www.peise.net/color/1.html',
    name: '古铜色',
    color: '#b87333',
    rcolor: '#47c5cc' },
  { url: 'http://www.peise.net/color/2.html',
    name: '薄荷冰淇淋色',
    color: '#f5fffb',
    rcolor: '#0a0004' },
  { url: 'http://www.peise.net/color/2.html',
    name: '草坪绿',
    color: '#7cfc00',
    rcolor: '#c103ff' },
  { url: 'http://www.peise.net/color/2.html',
    name: '淡金色',
    color: '#eee8aa',
    rcolor: '#111755' },
  { url: 'http://www.peise.net/color/2.html',
    name: '法鲁红',
    color: '#801818',
    rcolor: '#bfe7e7' },
  { url: 'http://www.peise.net/color/2.html',
    name: '狼毛灰',
    color: '#d9d6cf',
    rcolor: '#262930' },
  { url: 'http://www.peise.net/color/2.html',
    name: '酸橙黄',
    color: '#ccff00',
    rcolor: '#3300ff' },
  { url: 'http://www.peise.net/color/2.html',
    name: '浅鲑鱼红',
    color: '#ffa07b',
    rcolor: '#005fc1' },
  { url: 'http://www.peise.net/color/2.html',
    name: '野草莓色',
    color: '#ff3399',
    rcolor: '#00cc66' },
  { url: 'http://www.peise.net/color/2.html',
    name: '狐色',
    color: '#96582a',
    rcolor: '#b4a7d5' },
  { url: 'http://www.peise.net/color/2.html',
    name: '杜若色',
    color: '#426ab3',
    rcolor: '#bdca4c' },
  { url: 'http://www.peise.net/color/2.html',
    name: '铅丹色',
    color: '#f3715c',
    rcolor: '#0cc6a3' },
  { url: 'http://www.peise.net/color/2.html',
    name: '莺色',
    color: '#87843b',
    rcolor: '#bbbdc4' },
  { url: 'http://www.peise.net/color/2.html',
    name: '浅缥色',
    color: '#228fbd',
    rcolor: '#ddb742' },
  { url: 'http://www.peise.net/color/2.html',
    name: '瑠璃色',
    color: '#2a5caa',
    rcolor: '#d5a355' },
  { url: 'http://www.peise.net/color/2.html',
    name: '若緑色',
    color: '#7fb80e',
    rcolor: '#bf47f1' },
  { url: 'http://www.peise.net/color/2.html',
    name: '郁金色',
    color: '#fdb933',
    rcolor: '#0246cc' },
  { url: 'http://www.peise.net/color/2.html',
    name: '肉桂色',
    color: '#da765b',
    rcolor: '#25c4a4' },
  { url: 'http://www.peise.net/color/2.html',
    name: '萌葱色',
    color: '#006c54',
    rcolor: '#ffc9ab' },
  { url: 'http://www.peise.net/color/2.html',
    name: '勿忘草色',
    color: '#7bbfea',
    rcolor: '#c14015' },
  { url: 'http://www.peise.net/color/2.html',
    name: '江戸紫',
    color: '#6f599c',
    rcolor: '#c7a663' },
  { url: 'http://www.peise.net/color/3.html',
    name: '亚麻色',
    color: '#b69968',
    rcolor: '#4966cb' },
  { url: 'http://www.peise.net/color/3.html',
    name: '薄柿色',
    color: '#ca8687',
    rcolor: '#35bcbb' },
  { url: 'http://www.peise.net/color/3.html',
    name: '青苔色',
    color: '#5c7a29',
    rcolor: '#a3c2d6' },
  { url: 'http://www.peise.net/color/3.html',
    name: '抹茶色',
    color: '#b7ba6b',
    rcolor: '#4845c9' },
  { url: 'http://www.peise.net/color/3.html',
    name: '水浅葱色',
    color: '#70a19f',
    rcolor: '#c75e60' },
  { url: 'http://www.peise.net/color/3.html',
    name: '少女肤色',
    color: '#fedcbd',
    rcolor: '#012342' },
  { url: 'http://www.peise.net/color/3.html',
    name: '黒茶色',
    color: '#563624',
    rcolor: '#a9c9db' },
  { url: 'http://www.peise.net/color/3.html',
    name: '隐匿的绿',
    color: '#051405',
    rcolor: '#faebfa' },
  { url: 'http://www.peise.net/color/3.html',
    name: '粉色口红',
    color: '#ff0090',
    rcolor: '#00ffb7' },
  { url: 'http://www.peise.net/color/3.html',
    name: '湖蓝色',
    color: '#00ebc0',
    rcolor: '#ff143f' },
  { url: 'http://www.peise.net/color/3.html',
    name: '赤褐色',
    color: '#835c25',
    rcolor: '#bda3da' },
  { url: 'http://www.peise.net/color/3.html',
    name: '忍冬藤色',
    color: '#e46084',
    rcolor: '#1b9fbd' },
  { url: 'http://www.peise.net/color/3.html',
    name: '圣诞蓝',
    color: '#2a8fbd',
    rcolor: '#d5b742' },
  { url: 'http://www.peise.net/color/3.html',
    name: '粉红圣诞',
    color: '#ff84ba',
    rcolor: '#00bd45' },
  { url: 'http://www.peise.net/color/3.html',
    name: '圣诞红',
    color: '#bf0a10',
    rcolor: '#40f5ef' },
  { url: 'http://www.peise.net/color/3.html',
    name: '圣诞绿色',
    color: '#20f856',
    rcolor: '#df07a9' },
  { url: 'http://www.peise.net/color/3.html',
    name: '冬季树',
    color: '#171916',
    rcolor: '#e8e6e9' },
  { url: 'http://www.peise.net/color/3.html',
    name: '冬季黄昏',
    color: '#4c556e',
    rcolor: '#b3aac8' },
  { url: 'http://www.peise.net/color/3.html',
    name: '暗潮',
    color: '#283734',
    rcolor: '#d7c8cb' },
  { url: 'http://www.peise.net/color/3.html',
    name: '灰质偏黄',
    color: '#eee7ce',
    rcolor: '#111831' },
  { url: 'http://www.peise.net/color/4.html',
    name: '灰质偏紫',
    color: '#ada0a5',
    rcolor: '#525f5a' },
  { url: 'http://www.peise.net/color/4.html',
    name: '皮革阴影',
    color: '#16110b',
    rcolor: '#e9eef4' },
  { url: 'http://www.peise.net/color/4.html',
    name: '潮湿的草',
    color: '#515733',
    rcolor: '#aea8cc' },
  { url: 'http://www.peise.net/color/4.html',
    name: '柔和蓝',
    color: '#9999ff',
    rcolor: '#666600' },
  { url: 'http://www.peise.net/color/4.html',
    name: '芥末色',
    color: '#c1d169',
    rcolor: '#3e2eca' },
  { url: 'http://www.peise.net/color/4.html',
    name: '粉蓝色',
    color: '#ccccff',
    rcolor: '#333300' },
  { url: 'http://www.peise.net/color/4.html',
    name: '埃及红',
    color: '#b05b5c',
    rcolor: '#4fa4a3' },
  { url: 'http://www.peise.net/color/4.html',
    name: '宝塔红',
    color: '#9c5657',
    rcolor: '#63a9a8' },
  { url: 'http://www.peise.net/color/4.html',
    name: '岩石红',
    color: '#d4cdc9',
    rcolor: '#2b3236' },
  { url: 'http://www.peise.net/color/4.html',
    name: '胭脂扣',
    color: '#ce90a2',
    rcolor: '#31b75d' },
  { url: 'http://www.peise.net/color/4.html',
    name: '红尘往事',
    color: '#be7591',
    rcolor: '#41c4b6' },
  { url: 'http://www.peise.net/color/4.html',
    name: '经典粉',
    color: '#c691a9',
    rcolor: '#39b656' },
  { url: 'http://www.peise.net/color/4.html',
    name: ' 梦想的颜色',
    color: '#06b9d1',
    rcolor: '#f9462e' },
  { url: 'http://www.peise.net/color/4.html',
    name: '紫绢色',
    color: '#b57795',
    rcolor: '#4ac3b4' },
  { url: 'http://www.peise.net/color/4.html',
    name: '雪玫瑰色',
    color: '#c78da8',
    rcolor: '#38b857' },
  { url: 'http://www.peise.net/color/4.html',
    name: '白葡萄酒色',
    color: '#fdfcf9',
    rcolor: '#020306' },
  { url: 'http://www.peise.net/color/4.html',
    name: '花季色',
    color: '#e3aacb',
    rcolor: '#1c5534' },
  { url: 'http://www.peise.net/color/4.html',
    name: '甜蜜公主',
    color: '#edc8dc',
    rcolor: '#123723' },
  { url: 'http://www.peise.net/color/4.html',
    name: '烛光色',
    color: '#f9ecf1',
    rcolor: '#06130e' },
  { url: 'http://www.peise.net/color/4.html',
    name: '雪山霞光',
    color: '#f8f1f0',
    rcolor: '#070e0f' },
  { url: 'http://www.peise.net/color/5.html',
    name: '清香李子',
    color: '#99758d',
    rcolor: '#66c4b8' },
  { url: 'http://www.peise.net/color/5.html',
    name: '马鞭草',
    color: '#af8da5',
    rcolor: '#50b85a' },
  { url: 'http://www.peise.net/color/5.html',
    name: '旷谷幽兰',
    color: '#c1a3b8',
    rcolor: '#3e5c47' },
  { url: 'http://www.peise.net/color/5.html',
    name: '悠悠若兰',
    color: '#d8c2d0',
    rcolor: '#273d2f' },
  { url: 'http://www.peise.net/color/5.html',
    name: '西洋丁香',
    color: '#e1cfd8',
    rcolor: '#1e3027' },
  { url: 'http://www.peise.net/color/5.html',
    name: '神秘紫韵',
    color: '#9d7294',
    rcolor: '#62c6b5' },
  { url: 'http://www.peise.net/color/5.html',
    name: '玉液琼浆',
    color: '#b48baa',
    rcolor: '#4bb955' },
  { url: 'http://www.peise.net/color/5.html',
    name: '梦幻佳人',
    color: '#c19db8',
    rcolor: '#3e6247' },
  { url: 'http://www.peise.net/color/5.html',
    name: '绣线菊',
    color: '#d9bfd2',
    rcolor: '#26402d' },
  { url: 'http://www.peise.net/color/5.html',
    name: '幽幽熏草',
    color: '#ece1e3',
    rcolor: '#131e1c' },
  { url: 'http://www.peise.net/color/5.html',
    name: '思念色',
    color: '#fafbfb',
    rcolor: '#050404' },
  { url: 'http://www.peise.net/color/5.html',
    name: '香水草',
    color: '#70186f',
    rcolor: '#c7e7c7' },
  { url: 'http://www.peise.net/color/5.html',
    name: '蝴蝶花',
    color: '#8a0060',
    rcolor: '#baff9f' },
  { url: 'http://www.peise.net/color/5.html',
    name: '古代紫',
    color: '#d1abc0',
    rcolor: '#2e543f' },
  { url: 'http://www.peise.net/color/5.html',
    name: '暗紫色',
    color: '#821a7d',
    rcolor: '#bee5c0' },
  { url: 'http://www.peise.net/color/5.html',
    name: '虹膜色',
    color: '#8f76ad',
    rcolor: '#b7c452' },
  { url: 'http://www.peise.net/color/5.html',
    name: '暗紫罗兰',
    color: '#733c80',
    rcolor: '#c5c3bf' },
  { url: 'http://www.peise.net/color/5.html',
    name: '青紫色',
    color: '#725c9e',
    rcolor: '#c6a361' },
  { url: 'http://www.peise.net/color/5.html',
    name: '灰紫色',
    color: '#c4b1be',
    rcolor: '#3b4e41' },
  { url: 'http://www.peise.net/color/5.html',
    name: '紫水晶',
    color: '#7b4885',
    rcolor: '#c1b7bc' },
  { url: 'http://www.peise.net/color/6.html',
    name: '李子色',
    color: '#b31e72',
    rcolor: '#4ce1c6' },
  { url: 'http://www.peise.net/color/6.html',
    name: '红紫色',
    color: '#b50079',
    rcolor: '#4affc2' },
  { url: 'http://www.peise.net/color/6.html',
    name: '兰紫色',
    color: '#943d92',
    rcolor: '#b5c2b6' },
  { url: 'http://www.peise.net/color/6.html',
    name: '紫色',
    color: '#8f0783',
    rcolor: '#b7f8bd' },
  { url: 'http://www.peise.net/color/6.html',
    name: '菖蒲色',
    color: '#ba79b1',
    rcolor: '#45c24e' },
  { url: 'http://www.peise.net/color/6.html',
    name: '丁香',
    color: '#bca1cc',
    rcolor: '#435e33' },
  { url: 'http://www.peise.net/color/6.html',
    name: '紫藤色',
    color: '#7d4f9e',
    rcolor: '#c0b061' },
  { url: 'http://www.peise.net/color/6.html',
    name: '薰衣草',
    color: '#d4c1dc',
    rcolor: '#2b3e23' },
  { url: 'http://www.peise.net/color/6.html',
    name: '薄墨色',
    color: '#a2a3a2',
    rcolor: '#5d5c5d' },
  { url: 'http://www.peise.net/color/6.html',
    name: '消炭色',
    color: '#4f4d4d',
    rcolor: '#b0b2b2' },
  { url: 'http://www.peise.net/color/6.html',
    name: '中黄黑',
    color: '#543f31',
    rcolor: '#abc0ce' },
  { url: 'http://www.peise.net/color/6.html',
    name: '濡雨色',
    color: '#000a00',
    rcolor: '#fff5ff' },
  { url: 'http://www.peise.net/color/6.html',
    name: '铅色',
    color: '#7e8282',
    rcolor: '#c0bebe' },
  { url: 'http://www.peise.net/color/6.html',
    name: '青灰色',
    color: '#68786c',
    rcolor: '#cbc3c9' },
  { url: 'http://www.peise.net/color/6.html',
    name: '青绿灰',
    color: '#90a691',
    rcolor: '#b759b6' },
  { url: 'http://www.peise.net/color/6.html',
    name: '鸠羽灰',
    color: '#9c898e',
    rcolor: '#63bab8' },
  { url: 'http://www.peise.net/color/6.html',
    name: '青白灰',
    color: '#9ba88d',
    rcolor: '#6457b8' },
  { url: 'http://www.peise.net/color/6.html',
    name: '赤白灰',
    color: '#d6a78b',
    rcolor: '#2958b9' },
  { url: 'http://www.peise.net/color/6.html',
    name: '黄灰色',
    color: '#b58d4c',
    rcolor: '#4ab8b3' },
  { url: 'http://www.peise.net/color/6.html',
    name: '黑灰色',
    color: '#544946',
    rcolor: '#abb6b9' },
  { url: 'http://www.peise.net/color/7.html',
    name: '锈玫瑰色',
    color: '#b8989c',
    rcolor: '#47b363' },
  { url: 'http://www.peise.net/color/7.html',
    name: '浅灰',
    color: '#9c9ea1',
    rcolor: '#63615e' },
  { url: 'http://www.peise.net/color/7.html',
    name: '中灰',
    color: '#828281',
    rcolor: '#bebebe' },
  { url: 'http://www.peise.net/color/7.html',
    name: '灰汁色',
    color: '#bfb691',
    rcolor: '#4049b6' },
  { url: 'http://www.peise.net/color/7.html',
    name: '空五倍子色',
    color: '#99876d',
    rcolor: '#66bbc8' },
  { url: 'http://www.peise.net/color/7.html',
    name: '贝色',
    color: '#fcfcf5',
    rcolor: '#03030a' },
  { url: 'http://www.peise.net/color/7.html',
    name: '蓝鼠',
    color: '#5f7896',
    rcolor: '#a0c3b4' },
  { url: 'http://www.peise.net/color/7.html',
    name: '砖青色',
    color: '#6483b0',
    rcolor: '#9bbd4f' },
  { url: 'http://www.peise.net/color/7.html',
    name: '铁青',
    color: '#344069',
    rcolor: '#cbbfca' },
  { url: 'http://www.peise.net/color/7.html',
    name: '浓蓝色',
    color: '#005a78',
    rcolor: '#ffa5c3' },
  { url: 'http://www.peise.net/color/7.html',
    name: '鼠尾草',
    color: '#5875ad',
    rcolor: '#a7c452' },
  { url: 'http://www.peise.net/color/7.html',
    name: '海军蓝',
    color: '#00466b',
    rcolor: '#ffb9c9' },
  { url: 'http://www.peise.net/color/7.html',
    name: '宝蓝色',
    color: '#005687',
    rcolor: '#ffa9bb' },
  { url: 'http://www.peise.net/color/7.html',
    name: '深青灰',
    color: '#004e78',
    rcolor: '#ffb1c3' },
  { url: 'http://www.peise.net/color/7.html',
    name: '天青色',
    color: '#87c4ed',
    rcolor: '#bb3b12' },
  { url: 'http://www.peise.net/color/7.html',
    name: '青金色',
    color: '#144099',
    rcolor: '#ebbf66' },
  { url: 'http://www.peise.net/color/7.html',
    name: '蓝黑色',
    color: '#05173b',
    rcolor: '#fae8c4' },
  { url: 'http://www.peise.net/color/7.html',
    name: '群青',
    color: '#003d99',
    rcolor: '#ffc266' },
  { url: 'http://www.peise.net/color/7.html',
    name: '琉璃色',
    color: '#1a4fa3',
    rcolor: '#e5b05c' },
  { url: 'http://www.peise.net/color/7.html',
    name: '水蓝色',
    color: '#58c3e0',
    rcolor: '#a73c1f' },
  { url: 'http://www.peise.net/color/8.html',
    name: '浓蓝紫色',
    color: '#001c54',
    rcolor: '#ffe3ab' },
  { url: 'http://www.peise.net/color/8.html',
    name: '石青色',
    color: '#0079ba',
    rcolor: '#ffc245' },
  { url: 'http://www.peise.net/color/8.html',
    name: '浅天色',
    color: '#abd6e0',
    rcolor: '#54291f' },
  { url: 'http://www.peise.net/color/8.html',
    name: '天色',
    color: '#95c4db',
    rcolor: '#b43b24' },
  { url: 'http://www.peise.net/color/8.html',
    name: '青蓝色',
    color: '#2883b0',
    rcolor: '#d7bd4f' },
  { url: 'http://www.peise.net/color/8.html',
    name: '浓蓝绿',
    color: '#006a80',
    rcolor: '#ffcabf' },
  { url: 'http://www.peise.net/color/8.html',
    name: '蓝绿色',
    color: '#00838f',
    rcolor: '#ffbdb7' },
  { url: 'http://www.peise.net/color/8.html',
    name: '瓷青',
    color: '#afe0e0',
    rcolor: '#501f1f' },
  { url: 'http://www.peise.net/color/8.html',
    name: '瓷绿',
    color: '#c8e6e2',
    rcolor: '#37191d' },
  { url: 'http://www.peise.net/color/8.html',
    name: '灰瓷',
    color: '#add4d9',
    rcolor: '#522b26' },
  { url: 'http://www.peise.net/color/8.html',
    name: '白青色',
    color: '#e4f4f5',
    rcolor: '#1b0b0a' },
  { url: 'http://www.peise.net/color/8.html',
    name: '萨克斯蓝',
    color: '#4d8aa8',
    rcolor: '#b2ba57' },
  { url: 'http://www.peise.net/color/8.html',
    name: '浅葱色',
    color: '#abd9e0',
    rcolor: '#54261f' },
  { url: 'http://www.peise.net/color/8.html',
    name: '地平线色',
    color: '#b4dbd4',
    rcolor: '#4b242b' },
  { url: 'http://www.peise.net/color/8.html',
    name: '绿白色',
    color: '#b2dbd5',
    rcolor: '#4d242a' },
  { url: 'http://www.peise.net/color/8.html',
    name: '绿瓷色',
    color: '#84c2b7',
    rcolor: '#bd3d48' },
  { url: 'http://www.peise.net/color/8.html',
    name: '海洋绿',
    color: '#209e85',
    rcolor: '#df61bc' },
  { url: 'http://www.peise.net/color/8.html',
    name: '青灰绿',
    color: '#428c6d',
    rcolor: '#bdb9c8' },
  { url: 'http://www.peise.net/color/8.html',
    name: '苹果绿',
    color: '#a0bd2b',
    rcolor: '#5f42d4' },
  { url: 'http://www.peise.net/color/8.html',
    name: '薄荷色',
    color: '#007850',
    rcolor: '#ffc3af' },
  { url: 'http://www.peise.net/color/9.html',
    name: '墨绿色',
    color: '#006650',
    rcolor: '#ff99af' },
  { url: 'http://www.peise.net/color/9.html',
    name: '翡翠绿',
    color: '#15ad66',
    rcolor: '#ea5299' },
  { url: 'http://www.peise.net/color/9.html',
    name: '铬绿色',
    color: '#6abd78',
    rcolor: '#ca42c3' },
  { url: 'http://www.peise.net/color/9.html',
    name: '叶绿色',
    color: '#83ad50',
    rcolor: '#bd52af' },
  { url: 'http://www.peise.net/color/9.html',
    name: '绿茶色',
    color: '#999e31',
    rcolor: '#6661ce' },
  { url: 'http://www.peise.net/color/9.html',
    name: '枯叶绿',
    color: '#aeba7f',
    rcolor: '#5145bf' },
  { url: 'http://www.peise.net/color/9.html',
    name: '草坪色',
    color: '#bdcc12',
    rcolor: '#4233ed' },
  { url: 'http://www.peise.net/color/9.html',
    name: '浅绿色',
    color: '#cce099',
    rcolor: '#331f66' },
  { url: 'http://www.peise.net/color/9.html',
    name: '春绿色',
    color: '#6bb073',
    rcolor: '#c94fc5' },
  { url: 'http://www.peise.net/color/9.html',
    name: '嫩绿色',
    color: '#a9cf53',
    rcolor: '#5630ac' },
  { url: 'http://www.peise.net/color/9.html',
    name: '闪光绿',
    color: '#d7e37f',
    rcolor: '#281cbf' },
  { url: 'http://www.peise.net/color/9.html',
    name: '灰菊色',
    color: '#e3dca1',
    rcolor: '#1c235e' },
  { url: 'http://www.peise.net/color/9.html',
    name: '土著黄',
    color: '#baa834',
    rcolor: '#4557cb' },
  { url: 'http://www.peise.net/color/9.html',
    name: '深卡机布色',
    color: '#877710',
    rcolor: '#bbc3ef' },
  { url: 'http://www.peise.net/color/9.html',
    name: '含羞草',
    color: '#edd340',
    rcolor: '#122cbf' },
  { url: 'http://www.peise.net/color/9.html',
    name: '芥子色',
    color: '#d6c560',
    rcolor: '#293a9f' },
  { url: 'http://www.peise.net/color/9.html',
    name: '秋菊色',
    color: '#ffef94',
    rcolor: '#0010b5' },
  { url: 'http://www.peise.net/color/9.html',
    name: '落叶黄',
    color: '#e8a600',
    rcolor: '#1759ff' },
  { url: 'http://www.peise.net/color/9.html',
    name: '金盏花',
    color: '#f5ab00',
    rcolor: '#0a54ff' },
  { url: 'http://www.peise.net/color/9.html',
    name: '铬黄色',
    color: '#fcd200',
    rcolor: '#032dff' },
  { url: 'http://www.peise.net/color/10.html',
    name: '浅土色',
    color: '#f2ca5c',
    rcolor: '#0d35a3' },
  { url: 'http://www.peise.net/color/10.html',
    name: '土色',
    color: '#c28e00',
    rcolor: '#3db8ff' },
  { url: 'http://www.peise.net/color/10.html',
    name: '黄土色',
    color: '#d69200',
    rcolor: '#29b6ff' },
  { url: 'http://www.peise.net/color/10.html',
    name: '卡机色',
    color: '#b08427',
    rcolor: '#4fbdd8' },
  { url: 'http://www.peise.net/color/10.html',
    name: '淡黄色',
    color: '#ffebb5',
    rcolor: '#00144a' },
  { url: 'http://www.peise.net/color/10.html',
    name: '卵色',
    color: '#ffdf78',
    rcolor: '#0020c3' },
  { url: 'http://www.peise.net/color/10.html',
    name: '月亮黄',
    color: '#ffef61',
    rcolor: '#00109e' },
  { url: 'http://www.peise.net/color/10.html',
    name: '香槟黄',
    color: '#f2eba7',
    rcolor: '#0d1458' },
  { url: 'http://www.peise.net/color/10.html',
    name: '茉莉色',
    color: '#f7f7d2',
    rcolor: '#08082d' },
  { url: 'http://www.peise.net/color/10.html',
    name: '暗黄色',
    color: '#decb00',
    rcolor: '#2134ff' },
  { url: 'http://www.peise.net/color/10.html',
    name: '鲜黄色',
    color: '#ffea00',
    rcolor: '#0015ff' },
  { url: 'http://www.peise.net/color/10.html',
    name: '胭脂红',
    color: '#b3495c',
    rcolor: '#4cb6a3' },
  { url: 'http://www.peise.net/color/10.html',
    name: '品红',
    color: '#c7006a',
    rcolor: '#38ffca' },
  { url: 'http://www.peise.net/color/10.html',
    name: '枯红',
    color: '#c27280',
    rcolor: '#3dc6bf' },
  { url: 'http://www.peise.net/color/10.html',
    name: '宝石红',
    color: '#c70851',
    rcolor: '#38f7ae' },
  { url: 'http://www.peise.net/color/10.html',
    name: '浓酒红',
    color: '#66182c',
    rcolor: '#99e7d3' },
  { url: 'http://www.peise.net/color/10.html',
    name: '深红',
    color: '#c24630',
    rcolor: '#3db9cf' },
  { url: 'http://www.peise.net/color/10.html',
    name: '中国红',
    color: '#db4527',
    rcolor: '#24bad8' },
  { url: 'http://www.peise.net/color/10.html',
    name: '朱红',
    color: '#eb5528',
    rcolor: '#14aad7' },
  { url: 'http://www.peise.net/color/10.html',
    name: '玫瑰粉',
    color: '#ed859a',
    rcolor: '#12bc65' },
  { url: 'http://www.peise.net/color/11.html',
    name: '红梅粉',
    color: '#f7c6c7',
    rcolor: '#083938' },
  { url: 'http://www.peise.net/color/11.html',
    name: '蔷薇色',
    color: '#e61c62',
    rcolor: '#19e39d' },
  { url: 'http://www.peise.net/color/11.html',
    name: '浅山茶色',
    color: '#f5ddda',
    rcolor: '#0a2225' },
  { url: 'http://www.peise.net/color/11.html',
    name: '山茶色',
    color: '#d65a6f',
    rcolor: '#29a5c7' },
  { url: 'http://www.peise.net/color/11.html',
    name: '山茶粉',
    color: '#eb5e7c',
    rcolor: '#14a1c1' },
  { url: 'http://www.peise.net/color/11.html',
    name: '牡丹红',
    color: '#d6006f',
    rcolor: '#29ffc7' },
  { url: 'http://www.peise.net/color/11.html',
    name: '浅粉色',
    color: '#fad7d9',
    rcolor: '#052826' },
  { url: 'http://www.peise.net/color/11.html',
    name: '浓粉色',
    color: '#f09091',
    rcolor: '#0fb7b6' },
  { url: 'http://www.peise.net/color/11.html',
    name: '薄红色',
    color: '#f29b88',
    rcolor: '#0d64bb' },
  { url: 'http://www.peise.net/color/11.html',
    name: '正红',
    color: '#d9210d',
    rcolor: '#26def2' },
  { url: 'http://www.peise.net/color/11.html',
    name: '浅绯色',
    color: '#de7062',
    rcolor: '#21c79d' },
  { url: 'http://www.peise.net/color/11.html',
    name: '深绯色',
    color: '#c7161c',
    rcolor: '#38e9e3' },
  { url: 'http://www.peise.net/color/11.html',
    name: '绯红色',
    color: '#e8251e',
    rcolor: '#17dae1' },
  { url: 'http://www.peise.net/color/11.html',
    name: '绯色',
    color: '#d4341c',
    rcolor: '#2bcbe3' },
  { url: 'http://www.peise.net/color/11.html',
    name: '驼色',
    color: '#b58453',
    rcolor: '#4abdac' },
  { url: 'http://www.peise.net/color/11.html',
    name: '咖啡色',
    color: '#733c12',
    rcolor: '#c5c3ed' },
  { url: 'http://www.peise.net/color/11.html',
    name: '米色',
    color: '#e3caa8',
    rcolor: '#1c3557' },
  { url: 'http://www.peise.net/color/11.html',
    name: '麦色',
    color: '#ccb281',
    rcolor: '#334dbe' },
  { url: 'http://www.peise.net/color/11.html',
    name: '沙尘色',
    color: '#d4b68c',
    rcolor: '#2b49b9' },
  { url: 'http://www.peise.net/color/11.html',
    name: '枯色',
    color: '#bfa173',
    rcolor: '#405ec5' },
  { url: 'http://www.peise.net/color/12.html',
    name: '绢色',
    color: '#ffc796',
    rcolor: '#0038b4' },
  { url: 'http://www.peise.net/color/12.html',
    name: '椰棕色',
    color: '#7a4917',
    rcolor: '#c2b6e8' },
  { url: 'http://www.peise.net/color/12.html',
    name: '沙茶色',
    color: '#f2d8ac',
    rcolor: '#0d2753' },
  { url: 'http://www.peise.net/color/12.html',
    name: '黄褐色',
    color: '#c28642',
    rcolor: '#3dbcbd' },
  { url: 'http://www.peise.net/color/12.html',
    name: '肤色',
    color: '#fac26e',
    rcolor: '#053dc8' },
  { url: 'http://www.peise.net/color/12.html',
    name: '梨色',
    color: '#fce1ae',
    rcolor: '#031e51' },
  { url: 'http://www.peise.net/color/12.html',
    name: '赭石',
    color: '#db8c37',
    rcolor: '#24b9c8' },
  { url: 'http://www.peise.net/color/12.html',
    name: '棕色',
    color: '#8c5119',
    rcolor: '#b9aee6' },
  { url: 'http://www.peise.net/color/12.html',
    name: '橘褐色',
    color: '#c75610',
    rcolor: '#38a9ef' },
  { url: 'http://www.peise.net/color/12.html',
    name: '秋橙色',
    color: '#e39139',
    rcolor: '#1cb6c6' },
  { url: 'http://www.peise.net/color/12.html',
    name: '沙棕色',
    color: '#a16d35',
    rcolor: '#5ec8ca' },
  { url: 'http://www.peise.net/color/12.html',
    name: '酱橙色',
    color: '#d17a00',
    rcolor: '#2ec2ff' },
  { url: 'http://www.peise.net/color/12.html',
    name: '黄橙色',
    color: '#e8a23a',
    rcolor: '#175dc5' },
  { url: 'http://www.peise.net/color/12.html',
    name: '浅橘色',
    color: '#f7b881',
    rcolor: '#0847be' },
  { url: 'http://www.peise.net/color/12.html',
    name: '热带橙',
    color: '#f2963a',
    rcolor: '#0db4c5' },
  { url: 'http://www.peise.net/color/12.html',
    name: '太阳橙',
    color: '#f28d00',
    rcolor: '#0db8ff' },
  { url: 'http://www.peise.net/color/12.html',
    name: '杏黄色',
    color: '#f5ad3b',
    rcolor: '#0a52c4' },
  { url: 'http://www.peise.net/color/12.html',
    name: '橘红色',
    color: '#ed6f00',
    rcolor: '#12c7ff' },
  { url: 'http://www.peise.net/color/12.html',
    name: '道奇蓝',
    color: '#1e90ff',
    rcolor: '#e1b700' },
  { url: 'http://www.peise.net/color/12.html',
    name: '柠檬薄纱色',
    color: '#fffacd',
    rcolor: '#000532' },
  { url: 'http://www.peise.net/color/13.html',
    name: '鹿皮色',
    color: '#ffe4b5',
    rcolor: '#001b4a' },
  { url: 'http://www.peise.net/color/13.html',
    name: '秘鲁色',
    color: '#cd853f',
    rcolor: '#32bcc0' },
  { url: 'http://www.peise.net/color/13.html',
    name: '浅鲜肉色',
    color: '#ffa07a',
    rcolor: '#005fc2' },
  { url: 'http://www.peise.net/color/13.html',
    name: '深鲜肉色',
    color: '#e9967a',
    rcolor: '#16b4c2' },
  { url: 'http://www.peise.net/color/13.html',
    name: '鲜肉色',
    color: '#fa8072',
    rcolor: '#05bfc6' },
  { url: 'http://www.peise.net/color/13.html',
    name: '暗淡的灰色',
    color: '#696969',
    rcolor: '#cacaca' },
  { url: 'http://www.peise.net/color/13.html',
    name: '灰色',
    color: '#808080',
    rcolor: '#bfbfbf' },
  { url: 'http://www.peise.net/color/13.html',
    name: '深灰色',
    color: '#a9a9a9',
    rcolor: '#565656' },
  { url: 'http://www.peise.net/color/13.html',
    name: '浅灰色',
    color: '#d3d3d3',
    rcolor: '#2c2c2c' },
  { url: 'http://www.peise.net/color/13.html',
    name: '烟白色',
    color: '#f5f5f5',
    rcolor: '#0a0a0a' },
  { url: 'http://www.peise.net/color/13.html',
    name: '深红色',
    color: '#8b0000',
    rcolor: '#b9ffff' },
  { url: 'http://www.peise.net/color/13.html',
    name: '暗红色',
    color: '#a52a2a',
    rcolor: '#5ad5d5' },
  { url: 'http://www.peise.net/color/13.html',
    name: '印度红',
    color: '#cd5c5c',
    rcolor: '#32a3a3' },
  { url: 'http://www.peise.net/color/13.html',
    name: '淡珊瑚色',
    color: '#f08080',
    rcolor: '#0fbfbf' },
  { url: 'http://www.peise.net/color/13.html',
    name: '雪白色',
    color: '#fffafa',
    rcolor: '#000505' },
  { url: 'http://www.peise.net/color/13.html',
    name: '薄雾玫瑰色',
    color: '#ffe4e1',
    rcolor: '#001b1e' },
  { url: 'http://www.peise.net/color/13.html',
    name: '番茄色',
    color: '#ff6347',
    rcolor: '#009cb8' },
  { url: 'http://www.peise.net/color/13.html',
    name: '橙红色',
    color: '#ff4500',
    rcolor: '#00baff' },
  { url: 'http://www.peise.net/color/13.html',
    name: '黄土赭色',
    color: '#a0522d',
    rcolor: '#5fadd2' },
  { url: 'http://www.peise.net/color/13.html',
    name: '海贝壳色',
    color: '#fff5ee',
    rcolor: '#000a11' },
  { url: 'http://www.peise.net/color/14.html',
    name: '马鞍棕色',
    color: '#8b4513',
    rcolor: '#b9baec' },
  { url: 'http://www.peise.net/color/14.html',
    name: '巧克力色',
    color: '#d2691e',
    rcolor: '#2dcae1' },
  { url: 'http://www.peise.net/color/14.html',
    name: '沙棕色',
    color: '#f4a460',
    rcolor: '#0b5b9f' },
  { url: 'http://www.peise.net/color/14.html',
    name: '桃色',
    color: '#ffdab9',
    rcolor: '#002546' },
  { url: 'http://www.peise.net/color/14.html',
    name: '亚麻布色',
    color: '#faf0e6',
    rcolor: '#050f19' },
  { url: 'http://www.peise.net/color/14.html',
    name: '深橙色',
    color: '#ff8c00',
    rcolor: '#00b9ff' },
  { url: 'http://www.peise.net/color/14.html',
    name: '杏白色',
    color: '#ffebcd',
    rcolor: '#001432' },
  { url: 'http://www.peise.net/color/14.html',
    name: '番木瓜色',
    color: '#ffefd5',
    rcolor: '#00102a' },
  { url: 'http://www.peise.net/color/14.html',
    name: '小麦色',
    color: '#f5deb3',
    rcolor: '#0a214c' },
  { url: 'http://www.peise.net/color/14.html',
    name: '花白色',
    color: '#fffaf0',
    rcolor: '#00050f' },
  { url: 'http://www.peise.net/color/14.html',
    name: '玉米色',
    color: '#fff8dc',
    rcolor: '#000723' },
  { url: 'http://www.peise.net/color/14.html',
    name: '卡其布色',
    color: '#f0e68c',
    rcolor: '#0f19b9' },
  { url: 'http://www.peise.net/color/14.html',
    name: '深卡其布色',
    color: '#bdb76b',
    rcolor: '#4248c9' },
  { url: 'http://www.peise.net/color/14.html',
    name: '橄榄色',
    color: '#808000',
    rcolor: '#bfbfff' },
  { url: 'http://www.peise.net/color/14.html',
    name: '麒麟黄',
    color: '#fafad2',
    rcolor: '#05052d' },
  { url: 'http://www.peise.net/color/14.html',
    name: '土褐橄榄色',
    color: '#556b2f',
    rcolor: '#aac9d0' },
  { url: 'http://www.peise.net/color/14.html',
    name: '绿黄色',
    color: '#adff2f',
    rcolor: '#5200d0' },
  { url: 'http://www.peise.net/color/14.html',
    name: '查特酒绿色',
    color: '#7fff00',
    rcolor: '#bf00ff' },
  { url: 'http://www.peise.net/color/14.html',
    name: '深绿色',
    color: '#006400',
    rcolor: '#ff9bff' },
  { url: 'http://www.peise.net/color/14.html',
    name: '森林绿',
    color: '#228b22',
    rcolor: '#ddb9dd' },
  { url: 'http://www.peise.net/color/15.html',
    name: '酸橙绿色',
    color: '#32cd32',
    rcolor: '#cd32cd' },
  { url: 'http://www.peise.net/color/15.html',
    name: '绿色',
    color: '#3cb371',
    rcolor: '#c34cc6' },
  { url: 'http://www.peise.net/color/15.html',
    name: '薄荷绿',
    color: '#00ff7f',
    rcolor: '#ff00bf' },
  { url: 'http://www.peise.net/color/15.html',
    name: '淡绿色',
    color: '#f5fffa',
    rcolor: '#0a0005' },
  { url: 'http://www.peise.net/color/15.html',
    name: '碧绿色',
    color: '#7fffaa',
    rcolor: '#bf0055' },
  { url: 'http://www.peise.net/color/15.html',
    name: '海洋绿',
    color: '#20b2aa',
    rcolor: '#df4d55' },
  { url: 'http://www.peise.net/color/15.html',
    name: '宝石绿',
    color: '#48d1cc',
    rcolor: '#b72e33' },
  { url: 'http://www.peise.net/color/15.html',
    name: '水鸭色',
    color: '#008080',
    rcolor: '#ffbfbf' },
  { url: 'http://www.peise.net/color/15.html',
    name: '深青色',
    color: '#008b8b',
    rcolor: '#ffb9b9' },
  { url: 'http://www.peise.net/color/15.html',
    name: '青石板灰',
    color: '#2f4f4f',
    rcolor: '#d0b0b0' },
  { url: 'http://www.peise.net/color/15.html',
    name: '绿宝石色',
    color: '#00ced1',
    rcolor: '#ff312e' },
  { url: 'http://www.peise.net/color/15.html',
    name: '绿宝石色',
    color: '#afeeee',
    rcolor: '#501111' },
  { url: 'http://www.peise.net/color/15.html',
    name: '淡青色',
    color: '#e1ffff',
    rcolor: '#1e0000' },
  { url: 'http://www.peise.net/color/15.html',
    name: '火药蓝',
    color: '#b0e0e6',
    rcolor: '#4f1f19' },
  { url: 'http://www.peise.net/color/15.html',
    name: '天蓝色',
    color: '#00bfff',
    rcolor: '#ff4000' },
  { url: 'http://www.peise.net/color/15.html',
    name: '天蓝色',
    color: '#87ceeb',
    rcolor: '#bb3114' },
  { url: 'http://www.peise.net/color/15.html',
    name: '淡蓝色',
    color: '#87cefa',
    rcolor: '#bb3105' },
  { url: 'http://www.peise.net/color/15.html',
    name: '爱丽丝蓝',
    color: '#f0f8ff',
    rcolor: '#0f0700' },
  { url: 'http://www.peise.net/color/15.html',
    name: '石板灰',
    color: '#708090',
    rcolor: '#c7bfb7' },
  { url: 'http://www.peise.net/color/15.html',
    name: '矢车菊蓝',
    color: '#6495ed',
    rcolor: '#9bb412' },
  { url: 'http://www.peise.net/color/16.html',
    name: '幽灵白',
    color: '#f8f8ff',
    rcolor: '#070700' },
  { url: 'http://www.peise.net/color/16.html',
    name: '极淡的紫色',
    color: '#e6e6fa',
    rcolor: '#191905' },
  { url: 'http://www.peise.net/color/16.html',
    name: '蓝灰色',
    color: '#6a5acd',
    rcolor: '#caa532' },
  { url: 'http://www.peise.net/color/16.html',
    name: '深紫罗兰色',
    color: '#8a2be2',
    rcolor: '#bad41d' },
  { url: 'http://www.peise.net/color/16.html',
    name: '靛青色',
    color: '#4b0082',
    rcolor: '#b4ffbe' },
  { url: 'http://www.peise.net/color/16.html',
    name: '深紫罗兰色',
    color: '#9400d3',
    rcolor: '#b5ff2c' },
  { url: 'http://www.peise.net/color/16.html',
    name: '兰紫色',
    color: '#ba55d3',
    rcolor: '#45aa2c' },
  { url: 'http://www.peise.net/color/16.html',
    name: '深洋红色',
    color: '#8b008b',
    rcolor: '#b9ffb9' },
  { url: 'http://www.peise.net/color/16.html',
    name: '洋红',
    color: '#ff00ff',
    rcolor: '#00ff00' },
  { url: 'http://www.peise.net/color/16.html',
    name: '紫罗兰',
    color: '#ee82ee',
    rcolor: '#11be11' },
  { url: 'http://www.peise.net/color/16.html',
    name: '红紫色',
    color: '#da70d6',
    rcolor: '#25c729' },
  { url: 'http://www.peise.net/color/16.html',
    name: '深粉色',
    color: '#ff1493',
    rcolor: '#00ebb5' },
  { url: 'http://www.peise.net/color/16.html',
    name: '粉红色',
    color: '#ff69b4',
    rcolor: '#00ca4b' },
  { url: 'http://www.peise.net/color/16.html',
    name: '紫罗兰红',
    color: '#db7093',
    rcolor: '#24c7b5' },
  { url: 'http://www.peise.net/color/16.html',
    name: '淡粉色',
    color: '#fff0f5',
    rcolor: '#000f0a' },
  { url: 'http://www.peise.net/color/16.html',
    name: '大红色',
    color: '#dc143c',
    rcolor: '#23ebc3' },
  { url: 'http://www.peise.net/color/16.html',
    name: '浅粉红',
    color: '#ffb6c1',
    rcolor: '#00493e' },
  { url: 'http://www.peise.net/color/16.html',
    name: '草绿色',
    color: '#86bd77',
    rcolor: '#bc42c3' },
  { url: 'http://www.peise.net/color/16.html',
    name: '少女粉',
    color: '#fdd3e1',
    rcolor: '#022c1e' },
  { url: 'http://www.peise.net/color/16.html',
    name: '晴空色',
    color: '#68bcdd',
    rcolor: '#cb4322' },
  { url: 'http://www.peise.net/color/17.html',
    name: '蔷薇色',
    color: '#d699ba',
    rcolor: '#296645' },
  { url: 'http://www.peise.net/color/17.html',
    name: '象牙黄',
    color: '#f1ecb9',
    rcolor: '#0e1346' },
  { url: 'http://www.peise.net/color/17.html',
    name: '迷人的粉红',
    color: '#e880a2',
    rcolor: '#17bf5d' },
  { url: 'http://www.peise.net/color/17.html',
    name: '玫瑰灰',
    color: '#918280',
    rcolor: '#b6bebf' },
  { url: 'http://www.peise.net/color/17.html',
    name: '暗紫灰',
    color: '#48414a',
    rcolor: '#b7beb5' },
  { url: 'http://www.peise.net/color/17.html',
    name: '贝壳色',
    color: '#ede6e1',
    rcolor: '#12191e' },
  { url: 'http://www.peise.net/color/17.html',
    name: '象牙色',
    color: '#e0d3bf',
    rcolor: '#1f2c40' },
  { url: 'http://www.peise.net/color/17.html',
    name: '珍珠灰',
    color: '#ababab',
    rcolor: '#545454' },
  { url: 'http://www.peise.net/color/17.html',
    name: '锡灰色',
    color: '#606968',
    rcolor: '#9fcacb' },
  { url: 'http://www.peise.net/color/17.html',
    name: '银灰色',
    color: '#a9a6ab',
    rcolor: '#565954' },
  { url: 'http://www.peise.net/color/17.html',
    name: '酒红色',
    color: '#a35568',
    rcolor: '#5caacb' },
  { url: 'http://www.peise.net/color/17.html',
    name: '玫瑰粉',
    color: '#edb9bd',
    rcolor: '#124642' },
  { url: 'http://www.peise.net/color/17.html',
    name: '杜鹃红',
    color: '#d97e96',
    rcolor: '#26c0b4' },
  { url: 'http://www.peise.net/color/17.html',
    name: '茄子色',
    color: '#6b6575',
    rcolor: '#c99ac4' },
  { url: 'http://www.peise.net/color/17.html',
    name: '樱桃色',
    color: '#f5edf1',
    rcolor: '#0a120e' },
  { url: 'http://www.peise.net/color/17.html',
    name: '兰花色',
    color: '#d9c1d7',
    rcolor: '#263e28' },
  { url: 'http://www.peise.net/color/17.html',
    name: '紫丁香',
    color: '#d4c1db',
    rcolor: '#2b3e24' },
  { url: 'http://www.peise.net/color/17.html',
    name: '欧薄荷',
    color: '#b8afc9',
    rcolor: '#475036' },
  { url: 'http://www.peise.net/color/17.html',
    name: '鸢尾科',
    color: '#8f74ad',
    rcolor: '#b7c552' },
  { url: 'http://www.peise.net/color/17.html',
    name: '葡萄色',
    color: '#4a1075',
    rcolor: '#b5efc4' },
  { url: 'http://www.peise.net/color/18.html',
    name: '灰鸽色',
    color: '#86869e',
    rcolor: '#bcbc61' },
  { url: 'http://www.peise.net/color/18.html',
    name: '紫锦葵',
    color: '#a08ab5',
    rcolor: '#5fba4a' },
  { url: 'http://www.peise.net/color/18.html',
    name: '淡紫色',
    color: '#b8bbde',
    rcolor: '#474421' },
  { url: 'http://www.peise.net/color/18.html',
    name: '深蓝紫色',
    color: '#575f96',
    rcolor: '#a8a0b4' },
  { url: 'http://www.peise.net/color/18.html',
    name: '铃铛花蓝',
    color: '#6a6db0',
    rcolor: '#cac84f' },
  { url: 'http://www.peise.net/color/18.html',
    name: '青金色',
    color: '#0077b8',
    rcolor: '#ffc347' },
  { url: 'http://www.peise.net/color/18.html',
    name: '午夜蓝',
    color: '#3d5363',
    rcolor: '#c2ac9c' },
  { url: 'http://www.peise.net/color/18.html',
    name: '普鲁士蓝',
    color: '#56718f',
    rcolor: '#a9c6b7' },
  { url: 'http://www.peise.net/color/18.html',
    name: '岩石蓝',
    color: '#759fbd',
    rcolor: '#c46042' },
  { url: 'http://www.peise.net/color/18.html',
    name: '嫩蓝色',
    color: '#bcd4e3',
    rcolor: '#432b1c' },
  { url: 'http://www.peise.net/color/18.html',
    name: '钴蓝色',
    color: '#0088c7',
    rcolor: '#ffbb38' },
  { url: 'http://www.peise.net/color/18.html',
    name: '蔚蓝色',
    color: '#008fd1',
    rcolor: '#ffb72e' },
  { url: 'http://www.peise.net/color/18.html',
    name: '靛青灰色',
    color: '#7495a6',
    rcolor: '#c5b459' },
  { url: 'http://www.peise.net/color/18.html',
    name: '水蓝色',
    color: '#b9dced',
    rcolor: '#462312' },
  { url: 'http://www.peise.net/color/18.html',
    name: '海蓝',
    color: '#00799e',
    rcolor: '#ffc261' },
  { url: 'http://www.peise.net/color/18.html',
    name: '绿松石蓝',
    color: '#00a6de',
    rcolor: '#ff5921' },
  { url: 'http://www.peise.net/color/18.html',
    name: '孔雀蓝',
    color: '#0090b0',
    rcolor: '#ffb74f' },
  { url: 'http://www.peise.net/color/18.html',
    name: '尼罗蓝',
    color: '#4fabc2',
    rcolor: '#b0543d' },
  { url: 'http://www.peise.net/color/18.html',
    name: '孔雀绿',
    color: '#0096b0',
    rcolor: '#ffb44f' },
  { url: 'http://www.peise.net/color/18.html',
    name: '烫绿色',
    color: '#426b6b',
    rcolor: '#bdc9c9' },
  { url: 'http://www.peise.net/color/19.html',
    name: '竹绿色',
    color: '#009ea3',
    rcolor: '#ff615c' },
  { url: 'http://www.peise.net/color/19.html',
    name: '浓绿色',
    color: '#008f81',
    rcolor: '#ffb7be' },
  { url: 'http://www.peise.net/color/19.html',
    name: '灰绿色',
    color: '#91bfbd',
    rcolor: '#b64042' },
  { url: 'http://www.peise.net/color/19.html',
    name: '酒绿色',
    color: '#426e62',
    rcolor: '#bdc89d' },
  { url: 'http://www.peise.net/color/19.html',
    name: '酒绿色',
    color: '#426e62',
    rcolor: '#bdc89d' },
  { url: 'http://www.peise.net/color/19.html',
    name: '孔雀石绿',
    color: '#009973',
    rcolor: '#ff66c5' },
  { url: 'http://www.peise.net/color/19.html',
    name: '钴绿色',
    color: '#57bdaa',
    rcolor: '#a84255' },
  { url: 'http://www.peise.net/color/19.html',
    name: '常绿色',
    color: '#00997a',
    rcolor: '#ff66c2' },
  { url: 'http://www.peise.net/color/19.html',
    name: '白绿色',
    color: '#cce6de',
    rcolor: '#331921' },
  { url: 'http://www.peise.net/color/19.html',
    name: '松叶绿',
    color: '#8aa184',
    rcolor: '#ba5ebd' },
  { url: 'http://www.peise.net/color/19.html',
    name: '翠绿色',
    color: '#a7b56b',
    rcolor: '#584ac9' },
  { url: 'http://www.peise.net/color/19.html',
    name: '橄榄绿',
    color: '#7c8260',
    rcolor: '#c1be9f' },
  { url: 'http://www.peise.net/color/19.html',
    name: '苔绿色',
    color: '#98a16a',
    rcolor: '#b35eca' },
  { url: 'http://www.peise.net/color/19.html',
    name: '淡茶色',
    color: '#d4c69f',
    rcolor: '#2b3960' },
  { url: 'http://www.peise.net/color/19.html',
    name: '柠檬黄',
    color: '#f0d800',
    rcolor: '#0f27ff' },
  { url: 'http://www.peise.net/color/19.html',
    name: '栗色',
    color: '#8c585f',
    rcolor: '#b9a7a0' },
  { url: 'http://www.peise.net/color/19.html',
    name: '西草红',
    color: '#bf6a67',
    rcolor: '#40cacb' },
  { url: 'http://www.peise.net/color/19.html',
    name: '残红色',
    color: '#e3aba1',
    rcolor: '#1c545e' },
  { url: 'http://www.peise.net/color/19.html',
    name: '婴儿粉',
    color: '#f5e2dc',
    rcolor: '#0a1d23' },
  { url: 'http://www.peise.net/color/19.html',
    name: '珊瑚粉',
    color: '#f2b0ac',
    rcolor: '#0d4f53' },
  { url: 'http://www.peise.net/color/20.html',
    name: '草莓红',
    color: '#c75872',
    rcolor: '#38a7c6' },
  { url: 'http://www.peise.net/color/20.html',
    name: '带灰紫的玫瑰色',
    color: '#d6a9aa',
    rcolor: '#295655' },
  { url: 'http://www.peise.net/color/20.html',
    name: '玫瑰红',
    color: '#de7683',
    rcolor: '#21c4bd' },
  { url: 'http://www.peise.net/color/20.html',
    name: '红紫色',
    color: '#c25988',
    rcolor: '#3da6bb' },
  { url: 'http://www.peise.net/color/20.html',
    name: '红橙色',
    color: '#db4e02',
    rcolor: '#24b1fd' },
  { url: 'http://www.peise.net/color/20.html',
    name: '深紫灰',
    color: '#806e6b',
    rcolor: '#bfc8c9' },
  { url: 'http://www.peise.net/color/20.html',
    name: '红豆色',
    color: '#b08c80',
    rcolor: '#4fb9bf' },
  { url: 'http://www.peise.net/color/20.html',
    name: '可可色',
    color: '#947665',
    rcolor: '#b5c49a' },
  { url: 'http://www.peise.net/color/20.html',
    name: '砖红色',
    color: '#b07b61',
    rcolor: '#4fc19e' },
  { url: 'http://www.peise.net/color/20.html',
    name: '杏仁色',
    color: '#e8bf9b',
    rcolor: '#174064' },
  { url: 'http://www.peise.net/color/20.html',
    name: '奶酪色',
    color: '#dec68a',
    rcolor: '#2139ba' },
  { url: 'http://www.peise.net/color/20.html',
    name: '奶油色',
    color: '#f2e8c4',
    rcolor: '#0d173b' },
  { url: 'http://www.peise.net/color/20.html',
    name: '金黄色',
    color: '#f5c400',
    rcolor: '#0a3bff' },
  { url: 'http://www.peise.net/color/20.html',
    name: '香蕉黄',
    color: '#ffe100',
    rcolor: '#001eff' },
  { url: 'http://www.peise.net/color/20.html',
    name: '橘色',
    color: '#edaf1f',
    rcolor: '#1250e0' },
  { url: 'http://www.peise.net/color/20.html',
    name: '连翘黄',
    color: '#ffe100',
    rcolor: '#001eff' },
  { url: 'http://www.peise.net/color/20.html',
    name: '金发色',
    color: '#dbc751',
    rcolor: '#2438ae' },
  { url: 'http://www.peise.net/color/20.html',
    name: '那不勒斯黄',
    color: '#f2d88f',
    rcolor: '#0d27b7' },
  { url: 'http://www.peise.net/color/20.html',
    name: '象牙黄',
    color: '#ede6da',
    rcolor: '#121925' },
  { url: 'http://www.peise.net/color/20.html',
    name: '黄赭石',
    color: '#d1ad69',
    rcolor: '#2e52ca' },
  { url: 'http://www.peise.net/color/21.html',
    name: '银白色',
    color: '#c5c8c9',
    rcolor: '#3a3736' },
  { url: 'http://www.peise.net/color/21.html',
    name: '金色',
    color: '#fac000',
    rcolor: '#053fff' },
  { url: 'http://www.peise.net/color/21.html',
    name: '浅粉色',
    color: '#f5b6b3',
    rcolor: '#0a494c' },
  { url: 'http://www.peise.net/color/21.html',
    name: '紫色水晶，紫罗兰',
    color: '#3d3461',
    rcolor: '#c2cb9e' },
  { url: 'http://www.peise.net/color/21.html',
    name: '海军蓝',
    color: '#00214f',
    rcolor: '#ffdeb0' },
  { url: 'http://www.peise.net/color/21.html',
    name: '深褐色',
    color: '#665856',
    rcolor: '#99a7a9' },
  { url: 'http://www.peise.net/color/21.html',
    name: '黄褐色',
    color: '#ab6900',
    rcolor: '#54caff' },
  { url: 'http://www.peise.net/color/21.html',
    name: '红褐色',
    color: '#8f695e',
    rcolor: '#b7caa1' },
  { url: 'http://www.peise.net/color/21.html',
    name: '深蓝色',
    color: '#12126e',
    rcolor: '#ededc8' },
  { url: 'http://www.peise.net/color/21.html',
    name: '红茶色',
    color: '#6e280e',
    rcolor: '#c8d7f1' },
  { url: 'http://www.peise.net/color/21.html',
    name: '褐色',
    color: '#946a2c',
    rcolor: '#b5cad3' },
  { url: 'http://www.peise.net/color/21.html',
    name: '粉红',
    color: '#edc2be',
    rcolor: '#123d41' },
  { url: 'http://www.peise.net/color/21.html',
    name: '紫红色',
    color: '#7d0043',
    rcolor: '#c0ffbc' },
  { url: 'http://www.peise.net/color/21.html',
    name: '紫色',
    color: '#4d157d',
    rcolor: '#b2eac0' },
  { url: 'http://www.peise.net/color/21.html',
    name: '偏蓝色的紫罗兰',
    color: '#002770',
    rcolor: '#ffd8c7' },
  { url: 'http://www.peise.net/color/21.html',
    name: '纯蓝色',
    color: '#005bab',
    rcolor: '#ffa454' },
  { url: 'http://www.peise.net/color/21.html',
    name: '蓝绿色',
    color: '#005a5c',
    rcolor: '#ffa5a3' },
  { url: 'http://www.peise.net/color/21.html',
    name: '纯绿色',
    color: '#008f0a',
    rcolor: '#ffb7f5' },
  { url: 'http://www.peise.net/color/21.html',
    name: '黄绿色',
    color: '#8ec21f',
    rcolor: '#b83de0' },
  { url: 'http://www.peise.net/color/21.html',
    name: '纯黄',
    color: '#fff200',
    rcolor: '#000dff' },
  { url: 'http://www.peise.net/color/22.html',
    name: '橙色',
    color: '#f29500',
    rcolor: '#0db4ff' },
  { url: 'http://www.peise.net/color/22.html',
    name: '测试颜色-纪念色彩',
    color: '#ff55ff',
    rcolor: '#00aa00' },
  { url: 'http://www.peise.net/color/22.html',
    name: '纯白',
    color: '#ffffff',
    rcolor: '#000000' },
  { url: 'http://www.peise.net/color/22.html',
    name: '纯黑',
    color: '#000000',
    rcolor: '#ffffff' } ];

var _ = require('underscore');
var len_cat = cats.length - 1;
var len_color = colors.length -1;

module.exports = function() {
  var idx_r_cat = _.random(0, len_cat);
  var r_cat = cats[idx_r_cat];
  var r_color = colors[_.random(0, len_color)];
  if( r_cat == undefined ){
    console.log( 'idx_r_cat', idx_r_cat);
  }
  return {
    name : r_color.name + '的' + r_cat,
    color : r_color.color,
    rcolor : r_color.rcolor
  };
}


;(require.main === module) && (function(){
  console.log( module.exports() );
})();